### ISSUE TITLE
"sans-serif"

### ISSUE THREAD

**Issue by gosoccerboy5** [BarelySmooth/barelysmooth.github.io#11]
you misspelled "sans-serif", so it appears as the default serif font for me :(
<img width="1290" alt="Screen Shot 2021-07-10 at 3 38 20 PM" src="https://user-images.githubusercontent.com/82768218/125175886-e054df00-e194-11eb-8351-3b59c875eb03.png">
https://github.com/BarelySmooth/barelysmooth.github.io/blob/fa46e0d1e1fe5ca00e212157e0608a9d52e7023d/404.html#L31

(while you're at it, could you link to the homepage on the 404 page?)

**Comment by BarelySmooth** [comment]
Thanks for finding this, I replaced `Roboto` with `Open Sans` because it looks similar to Segoe UI (which is only available on windows). I also corrected it to `sans-serif` :P

Edit: I also added a QR code and a link to the home page!
