### ISSUE TITLE
when is something great coming

### ISSUE THREAD

**Issue by gosoccerboy5** [BarelySmooth/barelysmooth.github.io#7]
it's been coming for, like, [almost 40 days](https://github.com/BarelySmooth/barelysmooth.github.io/commit/7e3ce05a26b25528507d9d3e28387a2738b4379f)

**Comment by BarelySmooth** [comment]
has it been 40 days already? 😯

I am still developing it - its just in another branch named ```proper-page```. I just added something like an intro yesterday!

**Comment by gosoccerboy5** [comment]
oh

**Comment by Quantum-Codes** [comment]
Tomorrow @gosoccerboy5

**Comment by BarelySmooth** [comment]
> Tomorrow @gosoccerboy5

But its just a single page at the moment , nothing much :P

**Comment by gosoccerboy5** [comment]
ive been waiting for this moment my whole life

**Comment by BarelySmooth** [comment]
done, only one page though 😄

**Comment by Quantum-Codes** [comment]
Scratch.mit.edu link doesn't work. BUT SO GOOOOOOD

**Comment by BarelySmooth** [comment]
> Scratch.mit.edu link doesn't work. BUT SO GOOOOOOD

Thanks!

Also, the scratch link was supposed to link to my scratch profile. Right now, I left it out intentionally. I'll add a (new) link there soon!

**Comment by Quantum-Codes** [comment]
I did. Just pull it

**Comment by gosoccerboy5** [comment]
this is great! I love how you're on my mouse on the 404 page

**Comment by gosoccerboy5** [comment]
something great came, so i will close this

**Comment by BarelySmooth** [comment]
> this is great! I love how you're on my mouse on the 404 page

thanks!
