### ISSUE TITLE
there's something called css margin

### ISSUE THREAD

**Issue by gosoccerboy5** [BarelySmooth/barelysmooth.github.io#8]
https://github.com/BarelySmooth/barelysmooth.github.io/blob/1ae21c0d0e89fb07d407a9b39376fee80c1f91c6/index.html#L43-L67

**Comment by BarelySmooth** [comment]
I just put it in there to see how the green thing will react on scroll. I should probably remove that

Edit: That intro thing works like a charm now 🚀
